name: Build & Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    name: Node 16 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - name: Restore Dependency Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Setup Testing Environment
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Git status check
        # here we check that there are no changed / new files from our test
        # run. we use `git status`, grep out the build zip (downloaded above),
        # and check if there are more than 0 lines in the output.
        run: if [[ $(git status --short | wc -l) -ne 0 ]]; then STATUS=$(git status --verbose); printf "%s" "$STATUS"; git diff | cat; exit 1; fi
        shell: bash

  format:
    name: Format
    uses: ./.github/workflows/format.yml
